# Generated by Django 5.0.2 on 2024-03-01 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_aboutme_client_contact_education_experience_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='img',
            field=models.CharField(max_length=255),
        ),
    ]
