# Generated by Django 5.0.2 on 2024-03-01 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_client_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='img',
            field=models.ImageField(upload_to='client/'),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='icon',
            field=models.CharField(max_length=255),
        ),
    ]
