# Generated by Django 5.0.2 on 2024-03-01 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_client_img_alter_profiles_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialSites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('icon', models.CharField(max_length=255)),
                ('url', models.URLField()),
            ],
        ),
    ]
